
name: Publish to NPM
permissions: write-all
on:
  workflow_dispatch:
    inputs:
        version:
          description: Environment for Deploy
          required: true
          type: choice
          options: 
            - patch
            - minor
            - major
jobs:
  publish:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
      
      - name: Clean
        uses: borales/actions-yarn@v4
        with:
          cmd: clean
      
      - name: Docs Clean 
        uses: borales/actions-yarn@v4
        with:
          cmd: docs:clean

      # - name: Build production bundle
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build:all

      # - name: Setup .yarnrc.yml
      #   run: |
      #     yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
      #     yarn config set npmScopes.my-org.npmAlwaysAuth true
      #     yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        uses: borales/actions-yarn@v4
        with:
          cmd: _release ${{ github.event.inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - run: git commit -a -m "bump version"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}

      # - name: Deploy with gh-pages
      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     yarn run docs:deploy -- -u "github-actions-bot <support+actions@github.com>"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Get Previous tag'
        id: currenttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: "unknown"
          
      - name: post message
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: post
          content: |
            post:
              zh_cn:
                title: ASUIKit 更新通知
                content:
                - - tag: text
                    un_escape: true
                    text: '更新版本：'
                  - tag: text
                    un_escape: true
                    text: ${{ steps.previoustag.outputs.tag }}
                - - tag: text
                    un_escape: true
                    text: 'NPM 地址:'
                  - tag: a
                    text: "@asuikit/core"
                    href: "https://www.npmjs.com/package/@asuikit/core"